services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    container_name: excel-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - .docker/app/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env
    networks:
      - excel
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:stable-alpine
    container_name: excel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - excel

  mysql:
    image: mysql:8.0
    container_name: excel-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: excel-import
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - excel

  redis:
    image: redis:alpine
    container_name: excel-redis
    ports:
      - "6379:6379"
    networks:
      - excel

volumes:
  db_data:

networks:
  excel:
    driver: bridge